development:
  sessions:
    default:
      database: kotoba_no_purobaida_development
      hosts:
        - localhost:<%= ENV['BOXEN_MONGODB_PORT'] || 27017 %>

test:
  sessions:
    default:
      database: kotoba_no_purobaida_test
      hosts:
        - localhost:<%= ENV['BOXEN_MONGODB_PORT'] || 27017 %>

production:
  sessions:
    default:
      database: kotoba_no_purobaida_production
      hosts:
        - localhost:27017